In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

In [3]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [4]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [ ]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#size=no of element
#itemsize=element size taken by each element

In [ ]:
import numpy as np

In [ ]:
array_1d = np.array([1, 2, 3, 4, 5, 6])
print("1D Array:")
print(array_1d)

1D Array:
[1 2 3 4 5 6]


In [ ]:
array_2d = array_1d.reshape(2, 3)
print("\nReshaped to 2D Array (2x3):")
print(array_2d)


Reshaped to 2D Array (2x3):
[[1 2 3]
 [4 5 6]]


In [ ]:
print("\nElement at position (1, 2):", array_2d[1, 2])


Element at position (1, 2): 6


In [ ]:
array_2d[0, 1] = 10
print("\nModified Array (After changing element at position (0,1) to 10):")
print(array_2d)


Modified Array (After changing element at position (0,1) to 10):
[[ 1 10  3]
 [ 4  5  6]]


In [ ]:
array_sum = np.sum(array_2d)
print("\nSum of all elements in the array:", array_sum)


Sum of all elements in the array: 29


In [ ]:
#CATEGORICAL ENCODEING
#One Hot Encoding:Each categories into seperate columns
#Label Encoding:Categories into numericals labels
#sklearn is a library